# Generated by Django 4.1.4 on 2023-01-10 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojas', '0002_alter_loja_endereco_delete_endereco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loja',
            name='endereco',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
